### ISSUE TITLE
Add associative scan

### ISSUE THREAD

**Issue by SamDuffield** [normal-computing/thermox#14]
We can get O(log(T)) time assuming O(T) cores for `sample` and `log_prob` by using `jax.lax.associative_scan`.

Relevant tensorflow code [here](https://github.com/tensorflow/probability/blob/v0.23.0/tensorflow_probability/python/experimental/parallel_filter/parallel_kalman_filter_lib.py#L130-L255)

**Comment by KaelanDt** [comment]
Note to change the handling of random seeds, such that `associative_scan=False` and `associative_scan=True` handle them in the same way

**Comment by KaelanDt** [comment]
Solved by https://github.com/normal-computing/thermox/pull/30
